
export var MANNEQUIN_BUBBLE_LOW = 0;
export var MANNEQUIN_BUBBLE_HIGH = 1;

export var MANNEQUIN_TEXTS = [
  "Um mit dem Experiment zu starten, musst du alle Materialien an der richtigen Stelle positionieren. Dafür musst du die Gegenstände greifen und zu dem blauen Hologramm ziehen. Wenn das Hologramm grün ist, kannst du deinen Gegenstand loslassen und den nächsten Gegenstand greifen.",
  "Als erstes musst du die Probe kräftig zerkleinern.",
  "Als nächstes musst du deine gemörserte Probe in den Tiegel einwiegen. Dafür musst du deinen Löffel zunächst im Mörser positionieren.",
  "Denk daran deine Waage immer erst auf null zu setzen.",
  "Füll nun genau 50g deiner Bodenprobe in den Tiegel auf der Waage.",
  "Super! Wenn du den Tiegel positioniert hast, zündest du den Bunsenbrenner mit dem Feuerzeug an und legst das Feuerzeug wieder zurück. Wenn du mit Feuer arbeitest, musst du die richtigen Handschuhe anziehen.",
  "Sobald du den Bunsenbrenner angedreht hast, läuft die Zeit.",
  "Rühr die Probe mit dem Glasstab um.",
  "Ich denke, es ist an der Zeit die Temperatur zu messen. Entferne zuerst den Glasstab aus dem Tiegel und leg ihn zurück auf die Arbeitsfläche.",
  "Denk daran die Probe regelmäßig umzurühren!",
  "Überprüfe die Temperatur regelmäßig. Die Probe darf nicht heißer als 500°C werden. Sollte die Temperatur über 500°C liegen musst du den Bunsenbrenner nach unten drehen. Leg das Thermometer wieder auf der Arbeitsfläche ab und rühr die Probe noch einmal um.",
  "Und schon bist du fertig. Dreh den Bunsenbrenner herunter und stell den Tiegel mit Hilfe der Tiegelzange auf den anderen Dreifuß und leg die Tiegelzange wieder ab. Jetzt musst du 20 Minuten warten, damit die Bodenprobe abkühlen kann.",
  "Nach dem Abkühlen muss die Probe erneut ausgewogen werden, um die Gewichtsdifferenz zu errechnen.",
  "Setz deine notierten Werte in die Formel ein.",
  "Schau dir die Steckbriefe zu deinem gewählten Ort an und versuche Erklärungen für deinen berechneten Humusgehalt zu finden!",
  "Das hast du wirklich super gemacht! Das Experiment Humusglühen ist jetzt beendet.",
  "Wenn man den Humusgehalt eines Bodens im Gelände bestimmen will, kann man ihn mit Hilfe einer Farbskala bewerten. Im Labor ist noch eine genauere Methode möglich. (...)",
  "Als erstes kannst du dich entscheiden, welchen Standort du näher untersuchen möchtest.",
  "Dies ist die falsche Antwort",
  "Hi! Schön, dass du den Weg in unser virtuelles Lehr-Lern-Labor gefunden hast. Ich bin die Laborleitung und werde dir durch meine Anleitung helfen das Experiment Humusglühen durchzuführen. An einigen Stellen wirst du den Button „Tipp“ sehen, der dir weitere Hilfestellungen geben wird.",
  "Leg den Glasstab wieder auf die Arbeitsfläche",
  "",
  "",
  "",
  "",
  "Hallo ! Willkommen bei Experiment 2 beta !",
  "Hi! Schön, dass du den Weg ins unser virtuelles Lehr-Lern-Labor gefunden hast. Ich bin die Laborleitung und werde dir durch meine Anleitung helfen das Experiment durchzuführen. An einigen Stellen wirst du den Button „Tipp“ sehen, der dir weitere Hilfestellungen geben wird.",
  "Im Folgenden werden wir die Korngröße deines ausgewählten Bodens bestimmen. Nach abnehmender Korngröße werden drei Feinbodenarten unterschieden: Sand; Schluff und Ton. Jeder Boden setzt sich neben Wasser, Luft und organischen Substanzen aus den drei Feinbodenarten zusammen und hat dadurch charakteristische Eigenschaften.",
  "Als erstes kannst du dich entscheiden, welchen Standort du näher untersuchen möchtest.",
  "Um die Probe untersuchen zu können, habe ich sie bereits bei 105°C für 24 Stunden getrocknet.",
  "Zerkleiner die getrocknete Probe kräftig im Mörser.",
  "Vor dir siehst du eine Siebmaschine, mit der du die einzelnen Bestandteile deines Feinbodens durch unterschiedliche Siebgrößen voneinander trennen kannst. Stelle zuerst die Auffangschale, dann das feine Sieb (0,063mm) und zuletzt das gröbere Sieb (2mm) auf die Siebmaschine.",
  "Füll nun deine gemörserte Bodenprobe in die Siebmaschine ein.",
  "Verschließe die Maschine mit dem Deckel und den Schrauben, sodass nichts von deiner Bodenprobe im Raum landet. Nun kannst du die Siebmaschine starten. Das Sieben wird 5 Minuten dauern.",
  "Deine Bodenprobe ist fertig. Nachdem die Bestandteile auseinander gesiebt wurden, können wir sie jetzt wiegen. Öffne den Verschluss und lege das grobe Sieb zur Seite. Der Boden, der sich darin befindet, wird als Bodenskelett bezeichnet und ist für die Bestimmung der Bodenart nicht relevant.",
  "Platziere das erste Sieb auf der Waage und notiere das Gewicht. In diesem Sieb befinden sich die Bodenpartikel die eine Größe zwischen 2mm- 0,063mm haben, also die Sandfraktion. Denk aber daran, dass du das Eigengewicht des Siebs (245g) abziehen musst. ",
  "Nimm die Auffangschale, stelle sie auf die Waage und notiere das Gewicht. In der Auffangschale sind alle Bodenpartikel, die kleiner sind als 0,063mm, also die Ton-/Schlufffraktion. Wenn man diese Partikel voneinander trennen will, müsste man eine sogenannte Schlämmanalyse machen. Denk auch hier daran, dass du das Eigengewicht des Siebs (285g) abziehen musst. ",
  "Super das Experiment ist geschafft!",
  "",
  "",
  "",
  "",
  "Hi! Schön, dass du den Weg in unser virtuelles Labor gefunden hast. Ich bin Erni und werde dir durch meine Anleitung helfen den Versuch zum Pflanzenwachstum durchzuführen. Während des Experiments wirst du einige Fragen beantworten, bei denen ich dich unterstützen kann und dir Feedback gebe.",
  "Vor dir siehst du drei Wachstumsschränke. In einem Wachstumsschrank können natürliche, aber auch zukünftige klimatische Wachstumsbedingungen für Pflanzen präzise simuliert werden. Angesichts des sich verändernden Klimas können wir schauen, wie Pflanzen in Zukunft wachsen und, ob sie das überhaupt noch können.",
  "Beginnen wir mit dem Experiment! \nStell einen Topf mit einem Weizensamen in den dazugehörigen Wachstumsschrank.",
  "Schließ die Wachstumsschränke.",
  "An jedem Wachstumsschrank findest du eine Anzeigetafel mit fünf verschiedenen Parametern, die Einfluss auf das Wachstum von Pflanzen haben. Um zu verstehen, wie welcher Parameter das Wachstum beeinflusst, ändern wir immer nur einen Parameter während die anderen gleichbleiben. Ansonsten können wir nicht genau wissen, was der Ursprung der Veränderung ist.",
  "Du kannst dich nun entscheiden, ob du den Einfluss der Temperatur, der Kohlenstoffdioxid-Konzentration oder der Bodenart näher untersuchen möchtest. ",
  //CO₂_Konzentration
  "Auf den Anzeigetafeln der Wachstumsschränke kannst du die Einstellungen der Parameter sehen. Die CO2Konzentration wird sich bei den drei Wachstumsschränken unterscheiden, während die anderen Parameter gleichbleiben und den idealen Wachstumsbedingungen von Weizen entsprechen.",
  "Ich habe die unterschiedlichen CO2-Konzentrationen bereits für dich ausgewählt und eingestellt. Du findest sie auf der Anzeigetafel.",
  "In diesem Versuch untersuchen wir, welchen Einfluss eine höhere CO2- Konzentration auf das Wachstum von Weizenpflanzen hat.",
  "Noch ein Tipp: Lies die Fragen und Antworten gründlich und aufmerksam, bevor du antwortest!",
  //Temperatur
  "Auf den Anzeigetafeln der Wachstumsschränke kannst du die Einstellungen der Parameter sehen. Die Temperatur wird sich bei den drei Wachstumsschränken unterscheiden, während die anderen Parameter gleichbleiben und den idealen Wachstumsbedingungen von Weizen entsprechen. ",
  "Ich habe die unterschiedlichen Temperaturen bereits für dich ausgewählt und eingestellt. Du findest sie auf der Anzeigetafel.",
  "In diesem Versuch untersuchen wir, welchen Einfluss eine höhere Temperatur auf das Wachstum von Weizenpflanzen hat. ",
  "Noch ein Tipp: Lies die Fragen und Antworten gründlich und aufmerksam, bevor du antwortest!",
  //Bodenart
  "Auf den Anzeigetafeln der Wachstumsschränke kannst du die Einstellungen der Parameter sehen. Die Bodenart wird sich bei den drei Wachstumsschränken unterscheiden, während die anderen Parameter gleichbleiben und den idealen Wachstumsbedingungen von Weizen entsprechen.",
  "Ich habe die unterschiedlichen Bodenarten bereits für dich ausgewählt und eingestellt. Du findest sie auf der Anzeigetafel.",
  "In diesem Versuch untersuchen wir, welchen Einfluss verschiedene Bodenarten auf das Wachstum von Weizenpflanzen haben.",
  "Noch ein Tipp: Lies die Fragen und Antworten gründlich und aufmerksam, bevor du antwortest!",
  "Für das Experiment nutzen wir einen Vorteil des virtuellen Labors. Normalerweise müssten wir jetzt mehrere Wochen warten, um eine Veränderung der Pflanzen zu beobachten und zu analysieren. Wir werden einfach vorspulen.",
  "Nach 6 Wochen kannst du bereits die ersten Veränderungen deiner Pflanzen sehen. Beschreibe das Aussehen der Pflanzen und notiere die Unterschiede.",
  //Feedback erste Runde
  "Sehr gute Beobachtung!",
  "Das ist nicht die korrekte Antwort. Schau dir deine Pflanzen nochmal genau an. ",
  //Feedback zweite Runde 
  "Sehr gut! Deine Antwort ist korrekt.",
  //CO₂-Konzentartion
  "Deine Antwort ist leider nicht korrekt. Nach 6 Wochen haben alle drei Weizenpflanzen das gleiche Erscheinungsbild. \nDenk beim nächsten Mal daran, die Fragen und möglichen Antworten gründlich zu lesen.",
  //Temperatur
  "Deine Antwort ist leider nicht korrekt. Bereits nach 6 Wochen kann man auf den Blättern bei Pflanze 3 vereinzelte gelbe Flecken erkennen. \nDenk beim nächsten Mal daran die Fragen und Antworten gründlich zu lesen.",
  //Bodenart
  "Deine Antwort ist leider nicht korrekt. Der lehmige Tonboden schränkt schon nach 6 Wochen das Wachstum der Weizenpflanze ein. \nDenk beim nächsten Mal daran die Fragen und Antworten gründlich zu lesen.",
  "Als nächstes schauen wir uns die Veränderungen nach 12 Wochen an.",
  "Wir können zwar schon einen Unterschied im Wachstum der Pflanzen sehen, allerdings wollen wir das auch noch wissenschaftlich überprüfen, indem wir das Gewicht der Weizenpflanzen bestimmen.",
  /*70*/"Nimm die Schere, schneide damit den ganzen oberirdischen Teil deiner Weizenpflanze ab und leg ihn in die Petrischale. Wiederhole den Vorgang mit den anderen beiden Pflanzen.",
  "Platzier die Petrischalen nacheinander auf der Waage und notiere das Gewicht. Beachte, dass das Anfangsgewicht der Waage einen Wert von -0,300 kg anzeigt. Wir haben das Eigengewicht der Petrischale von 300 g bereits berücksichtigt.",
  //Feedback
  //CO₂-Konzentration
  "Super! Deine Antwort ist richtig.",
  "Das ist nicht korrekt. Denk daran, dass du die Pflanzen in absteigender Reihenfolge ordnen sollst. Die Pflanze mit dem höchsten Wert kommt also zuerst.",
  "Top! Du hast die richtige Lösung. Mach weiter so und bleib aufmerksam beim Beantworten der Fragen. ",
  "Leider ist deine Antwort nicht korrekt. Pflanze 3 wiegt 970 g bei einer Höhe von 87 cm und ist damit am stärksten gewachsen. Die richtige Reihenfolge ist daher 3-2-1.",
  //Temperatur
  "Leider ist deine Antwort nicht korrekt. Mit einer Höhe von 80 cm und 800 g ist Pflanze 1 am stärksten gewachsen, wodurch die richtige Reihenfolge 1-2-3 ist.",
  //Bodenart
  "Leider ist deine Antwort nicht korrekt. Die richtige Reihenfolge ist 1-3-2, da sich Pflanze 1 mit 800 g und einer Höhe von 80 cm am stärksten gewachsen ist.",
  //CO₂
  //Feedback erste Runde
  /*78*/"Sehr gut! Deine Antwort ist korrekt.",
  "Deine Antwort ist leider nicht korrekt. Versuch es gleich nochmal.",
  //Feedback zweite Runde
  "Gut gemacht! Du hast die Frage richtig beantwortet. ",
  "Deine Antwort ist leider nicht korrekt. Eine erhöhte CO2-Konzentration steigert das Wachstum von Weizenpflanzen. Allerdings leidet die Qualität des Weizens darunter, was auch Auswirkungen auf die Höhe der Erträge hat.",
  //Temperatur - richtige Antworten gleich wie bei CO₂
  //Feedback erste Runde
  "Deine Antwort ist leider nicht korrekt. Versuch es gleich nochmal.",
  //Feedback zweite Runde
  "Deine Antwort ist leider nicht korrekt. Weizen wächst am besten bei 25 °C. Bei Temperaturen über 25 °C zeigen Weizenpflanzen erste Anzeichen für Hitzestress wie gelb gefärbte oder verwelkte Blätter.",
  //Bodenart - richtige Antworten gleich wie bei CO₂
  //Feedback erste Runde
  "Deine Antwort ist leider nicht korrekt. Versuch es gleich nochmal.",
  //Feedback zweite Runde
  "Deine Antwort ist leider nicht korrekt. Jede Bodenart hat unterschiedliche Eigenschaften, die das Wachstum von Weizen beeinflussen. Für Weizenpflanzen sorgt ein schluffiger Lehmboden aufgrund seiner guten Wasserspeicherkapazität, seiner guten Durchwurzelbarkeit und der damit verbundenen einfachen Bearbeitung für ideales Wachstum.",
  "Super du hast es geschafft!",
  //ThirdExp04
  /*87*/
  "Platzier die Petrischalen nacheinander auf der Waage und notiere das Gewicht. Beachte, dass das Anfangsgewicht der Waage einen Wert von -0,300 kg anzeigt. Wir haben das Eigengewicht der Petrischale von 300 g bereits berücksichtigt.",
  "Ordne die Weizenpflanzen 1 bis 3 nach ihrer Größe und Gewicht in absteigender Reihenfolge.",
  "Super, deine Antwort ist richtig.",
  "Deine Antwort ist leider nicht korrekt. Denk daran, dass du die Pflanzen in absteigender Reihenfolge ordnen sollst. Die Pflanze mit dem höchsten Wert kommt also zuerst.",
  "Top! Du hast die richtige Lösung. Mach weiter so und bleib aufmerksam beim Beantworten der Fragen.",
  "Leider ist deine Antwort nicht korrekt. Pflanze 3 wiegt 970 g bei einer Höhe von 87 cm und ist damit am stärksten gewachsen. Die richtige Reihenfolge ist daher 3-2-1.",
  "Leider ist deine Antwort nicht korrekt. Mit einer Höhe von 80 cm und 800 g ist Pflanze 1 am stärksten gewachsen, wodurch die richtige Reihenfolge 1-2-3 ist.",
  "Leider ist deine Antwort nicht korrekt. Die richtige Reihenfolge ist 1-3-2, da sich Pflanze 1 mit 800 g und einer Höhe von 80 cm am stärksten gewachsen ist.",
]


export var MANNEQUIN_TEXTS_EXTRA = [
  "",
  "Stell den Mörser mit dem Stößel auf das Hologramm. Du kannst erst mit der Probe weitermachen, wenn die Probe ganz fein gemörsert ist und sich keine zusammenhängenden Klümpchen mehr darin befinden! Diese würden das Ergebnis verfälschen.",
  "Notier das Leergewicht vom Tiegel in deinem Notizbuch! Das ist wichtig, um am Ende den Humusgehalt berechnen zu können. ",
  "Dafür musst du die Taste „TARA“ drücken.",
  "Notier das Gewicht deiner Bodenprobe in deinem Notizbuch.",
  "",
  "",
  "Wenn du den Button „Rühren“ mehrfach  anklickst, läuft die Stoppuhr schneller.",
  "Stell das Thermometer in den Tiegel und achte auf die Temperatur. Leg das Thermometer anschließend wieder auf die Arbeitsfläche.",
  "Wenn du den Button „Rühren“ mehrfach  anklickst, läuft die Stoppuhr schneller.",
  "",
  "",
  "Nimm den Tiegel mit der Tiegelzange und stell sie auf die Waage. Lies das Gewicht ab und notier es in deinem Notizbuch.",
  "",
  "",
  "",
  "Mithilfe eines Bunsenbrenners wird die Bodenprobe für 25 Minuten erhitzt. Humus besteht aus abgestorbenen pflanzlichen und tierischen Stoffen und ist brennbar. Durch das Ausglühen kann über den Gewichtsverlust der prozentuale Humusgehalt der Probe berechnet werden. Und genau das werden wir jetzt im Labor machen!\n      ",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "Das Gewicht der Sandfraktion benötigst du, um die Gesamtmasse des Bodens aber auch um den prozentualen Anteil der Sandfraktion am Gesamtboden zu berechnen.",
  "Das Gewicht der Ton-/Schlufffraktion benötigst du, um die Gesamtmasse des Bodens, aber auch um den prozentualen Anteil der Ton-/Schlufffraktion am Gesamtboden zu berechnen.",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
]

export var MANNEQUIN_TEXTS_BUBBLES = [
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_LOW,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_LOW,
  MANNEQUIN_BUBBLE_LOW,
  MANNEQUIN_BUBBLE_LOW,
  MANNEQUIN_BUBBLE_LOW,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
]

