
export var MANNEQUIN_BUBBLE_LOW = 0;
export var MANNEQUIN_BUBBLE_HIGH = 1;

export var MANNEQUIN_TEXTS = [
  "Um mit dem Experiment zu starten, musst du alle Materialien an der richtigen Stelle positionieren. Dafür musst du die Gegenstände greifen und zu dem blauen Hologramm ziehen. Wenn das Hologramm grün ist, kannst du deinen Gegenstand loslassen und den nächsten Gegenstand greifen.",
  "Als erstes musst du die Probe kräftig zerkleinern.",
  "Als nächstes musst du deine gemörserte Probe in den Tiegel einwiegen. Dafür musst du deinen Löffel zunächst im Mörser positionieren.",
  "Denk daran deine Waage immer erst auf null zu setzen.",
  "Füll nun genau 50g deiner Bodenprobe in den Tiegel auf der Waage.",
  "Super! Wenn du den Tiegel positioniert hast, zündest du den Bunsenbrenner mit dem Feuerzeug an und legst das Feuerzeug wieder zurück. Wenn du mit Feuer arbeitest, musst du die richtigen Handschuhe anziehen.",
  "Sobald du den Bunsenbrenner angedreht hast, läuft die Zeit.",
  "Rühr die Probe mit dem Glasstab um.",
  "Ich denke, es ist an der Zeit die Temperatur zu messen. Entferne zuerst den Glasstab aus dem Tiegel und leg ihn zurück auf die Arbeitsfläche.",
  "Denk daran die Probe regelmäßig umzurühren!",
  "Überprüfe die Temperatur regelmäßig. Die Probe darf nicht heißer als 500°C werden. Sollte die Temperatur über 500°C liegen musst du den Bunsenbrenner nach unten drehen. Leg das Thermometer wieder auf der Arbeitsfläche ab und rühr die Probe noch einmal um.",
  "Und schon bist du fertig. Dreh den Bunsenbrenner herunter und stell den Tiegel mit Hilfe der Tiegelzange auf den anderen Dreifuß und leg die Tiegelzange wieder ab. Jetzt musst du 20 Minuten warten, damit die Bodenprobe abkühlen kann.",
  "Nach dem Abkühlen muss die Probe erneut ausgewogen werden, um die Gewichtsdifferenz zu errechnen.",
  "Setz deine notierten Werte in die Formel ein.",
  "Schau dir die Steckbriefe zu deinem gewählten Ort an und versuche Erklärungen für deinen berechneten Humusgehalt zu finden!",
  "Das hast du wirklich super gemacht! Das Experiment Humusglühen ist jetzt beendet.",
  "Wenn man den Humusgehalt eines Bodens im Gelände bestimmen will, kann man ihn mit Hilfe einer Farbskala bewerten. Im Labor ist noch eine genauere Methode möglich. (...)",
  "Als erstes kannst du dich entscheiden, welchen Standort du näher untersuchen möchtest.",
  "Dies ist die falsche Antwort",
  "Hi! Schön, dass du den Weg in unser virtuelles Lehr-Lern-Labor gefunden hast. Ich bin die Laborleitung und werde dir durch meine Anleitung helfen das Experiment Humusglühen durchzuführen. An einigen Stellen wirst du den Button „Tipp“ sehen, der dir weitere Hilfestellungen geben wird.",
  "Leg den Glasstab wieder auf die Arbeitsfläche",
  "",
  "",
  "",
  "",
  "Hallo ! Willkommen bei Experiment 2 beta !",
  "Hi! Schön, dass du den Weg ins unser virtuelles Lehr-Lern-Labor gefunden hast. Ich bin die Laborleitung und werde dir durch meine Anleitung helfen das Experiment durchzuführen. An einigen Stellen wirst du den Button „Tipp“ sehen, der dir weitere Hilfestellungen geben wird.",
  "Im Folgenden werden wir die Korngröße deines ausgewählten Bodens bestimmen. Nach abnehmender Korngröße werden drei Feinbodenarten unterschieden: Sand 0,063mm-2mm; Schluff 0,002-0,063mm und Ton < 0,002mm. Jeder Boden setzt sich neben Wasser, Luft und organischen Substanzen aus den drei Feinbodenarten zusammen und hat dadurch charakteristische Eigenschaften.",
  "Als erstes kannst du dich entscheiden, welchen Standort du näher untersuchen möchtest.",
  "Bevor Bodenproben weiterverarbeitet werden können, müssen diese für 24 Stunden bei 105°C getrocknet werden.",
  "Du kannst die getrocknete Bodenprobe nun im Mörser kräftig zerkleinern.",
  "Vor dir siehst du eine Siebmaschine, mit der du die einzelnen Bestandteile deines Feinbodens durch unterschiedliche Siebgrößen voneinander trennen kannst. Stelle die Auffangschale, das feine Sieb (0,063mm) und das gröbere Sieb (2mm) auf die Siebmaschine.",
  "Anschließend kannst du deine gemörserte Bodenprobe in die Siebmaschine einfüllen.",
  "Verschließe die Maschine mit dem Deckel und den Schrauben, sodass nichts von deiner Bodenprobe im Raum landet. Nun kannst du die Siebmaschine starten. Das Sieben wird ungefähr 5 Minuten dauern.",
  "Deine Bodenprobe ist fertig. Nachdem die Bestandteile auseinander gesiebt wurden, können wir sie jetzt wiegen. Öffne den Verschluss und lege das grobe Sieb zur Seite. Der Boden, der sich darin befindet, wird als Bodenskelett bezeichnet und ist für die Bestimmung der Bodenart nicht relevant.",
  "Platziere das 0,63 mm Sieb auf der Waage und notiere das Gewicht. In diesem Sieb befinden sich die Bodenpartikel die eine Größe zwischen 2mm- 0,063mm haben, also die Sandfraktion. Um den prozentualen Anteil der Sandfraktion zu berechnen, musst du deine notierten Werte in die Formel eintragen.",
  "Nimm die Auffangschale, stelle sie auf die Waage und notiere das Gewicht. In der Auffangschale sind alle Bodenpartikel, die kleiner sind als 0,063mm. Wenn man diese Partikel voneinander trennen will, müsste man eine sogenannte Schlämmanalyse machen. Um den prozentualen Anteil der Ton-/ Schlufffraktion zu berechnen musst du deine notierten Werte in die Formel eintragen.",
  "Super das Experiment ist geschafft!",
]


export var MANNEQUIN_TEXTS_EXTRA = [
  "",
  "Stell den Mörser mit dem Stößel auf das Hologramm. Du kannst erst mit der Probe weitermachen, wenn die Probe ganz fein gemörsert ist und sich keine zusammenhängenden Klümpchen mehr darin befinden! Diese würden das Ergebnis verfälschen.",
  "Notier das Leergewicht vom Tiegel in deinem Notizbuch! Das ist wichtig, um am Ende den Humusgehalt berechnen zu können. ",
  "Dafür musst du die Taste „TARA“ drücken.",
  "Notier das Gewicht deiner Bodenprobe in deinem Notizbuch.",
  "",
  "",
  "Wenn du den Button „Rühren“ mehrfach  anklickst, läuft die Stoppuhr schneller.",
  "Stell das Thermometer in den Tiegel und achte auf die Temperatur. Leg das Thermometer anschließend wieder auf die Arbeitsfläche.",
  "Wenn du den Button „Rühren“ mehrfach  anklickst, läuft die Stoppuhr schneller.",
  "",
  "",
  "Nimm den Tiegel mit der Tiegelzange und stell sie auf die Waage. Lies das Gewicht ab und notier es in deinem Notizbuch.",
  "",
  "",
  "",
  "Mithilfe eines Bunsenbrenners wird die Bodenprobe für 25 Minuten erhitzt. Humus besteht aus abgestorbenen pflanzlichen und tierischen Stoffen und ist brennbar. Durch das Ausglühen kann über den Gewichtsverlust der prozentuale Humusgehalt der Probe berechnet werden. Und genau das werden wir jetzt im Labor machen!\n      ",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "Denk daran, dass du das Gewicht des Siebs selbst (245g) abziehen musst.",
  "Denk daran, dass du das Gewicht der Auffangschale (285g) selbst abziehen musst.",
  "",
]

export var MANNEQUIN_TEXTS_BUBBLES = [
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_LOW,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_LOW,
  MANNEQUIN_BUBBLE_LOW,
  MANNEQUIN_BUBBLE_LOW,
  MANNEQUIN_BUBBLE_LOW,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
]

