
export var MANNEQUIN_BUBBLE_LOW = 0;
export var MANNEQUIN_BUBBLE_HIGH = 1;

export var MANNEQUIN_TEXTS = [
  "Um mit dem Experiment zu starten, musst du alle Materialien an der richtigen Stelle positionieren. Dafür musst du die Gegenstände greifen und zu dem blauen Hologramm ziehen. Wenn das Hologramm grün ist, kannst du deinen Gegenstand loslassen und den nächsten Gegenstand greifen.",
  "Als erstes musst du die Probe kräftig zerkleinern.",
  "Als nächstes musst du deine gemörserte Probe in den Tiegel einwiegen. Dafür musst du deinen Löffel zunächst im Mörser positionieren.",
  "Denk daran deine Waage immer erst auf null zu setzen.",
  "Füll nun genau 50g deiner Bodenprobe in den Tiegel auf der Waage.",
  "Super! Wenn du den Tiegel positioniert hast, zündest du den Bunsenbrenner mit dem Feuerzeug an und legst das Feuerzeug wieder zurück. Wenn du mit Feuer arbeitest, musst du die richtigen Handschuhe anziehen.",
  "Sobald du den Bunsenbrenner angedreht hast, läuft die Zeit.",
  "Rühr die Probe mit dem Glasstab um.",
  "Ich denke, es ist an der Zeit die Temperatur zu messen. Entferne zuerst den Glasstab aus dem Tiegel und leg ihn zurück auf die Arbeitsfläche.",
  "Denk daran die Probe regelmäßig umzurühren!",
  "Überprüfe die Temperatur regelmäßig. Die Probe darf nicht heißer als 500°C werden. Sollte die Temperatur über 500°C liegen musst du den Bunsenbrenner nach unten drehen. Leg das Thermometer wieder auf der Arbeitsfläche ab und rühr die Probe noch einmal um.",
  "Und schon bist du fertig. Dreh den Bunsenbrenner herunter und stell den Tiegel mit Hilfe der Tiegelzange auf den anderen Dreifuß und leg die Tiegelzange wieder ab. Jetzt musst du 20 Minuten warten, damit die Bodenprobe abkühlen kann.",
  "Nach dem Abkühlen muss die Probe erneut ausgewogen werden, um die Gewichtsdifferenz zu errechnen.",
  "Setz deine notierten Werte in die Formel ein.",
  "Schau dir die Steckbriefe zu deinem gewählten Ort an und versuche Erklärungen für deinen berechneten Humusgehalt zu finden!",
  "Das hast du wirklich super gemacht! Das Experiment Humusglühen ist jetzt beendet.",
  "Wenn man den Humusgehalt eines Bodens im Gelände bestimmen will, kann man ihn mit Hilfe einer Farbskala bewerten. Im Labor ist noch eine genauere Methode möglich. (...)",
  "Als erstes kannst du dich entscheiden, welchen Standort du näher untersuchen möchtest.",
  "Dies ist die falsche Antwort",
  "Hi! Schön, dass du den Weg in unser virtuelles Lehr-Lern-Labor gefunden hast. Ich bin die Laborleitung und werde dir durch meine Anleitung helfen das Experiment Humusglühen durchzuführen. An einigen Stellen wirst du den Button „Tipp“ sehen, der dir weitere Hilfestellungen geben wird.",
  "Leg den Glasstab wieder auf die Arbeitsfläche",
  "",
  "",
  "",
  "",
  "Hallo ! Willkommen bei Experiment 2 beta !",
  "Hi! Schön, dass du den Weg ins unser virtuelles Lehr-Lern-Labor gefunden hast. Ich bin die Laborleitung und werde dir durch meine Anleitung helfen das Experiment durchzuführen. An einigen Stellen wirst du den Button „Tipp“ sehen, der dir weitere Hilfestellungen geben wird.",
  "Im Folgenden werden wir die Korngröße deines ausgewählten Bodens bestimmen. Nach abnehmender Korngröße werden drei Feinbodenarten unterschieden: Sand; Schluff und Ton. Jeder Boden setzt sich neben Wasser, Luft und organischen Substanzen aus den drei Feinbodenarten zusammen und hat dadurch charakteristische Eigenschaften.",
  "Als erstes kannst du dich entscheiden, welchen Standort du näher untersuchen möchtest.",
  "Um die Probe untersuchen zu können, habe ich sie bereits bei 105°C für 24 Stunden getrocknet.",
  "Zerkleiner die getrocknete Probe kräftig im Mörser.",
  "Vor dir siehst du eine Siebmaschine, mit der du die einzelnen Bestandteile deines Feinbodens durch unterschiedliche Siebgrößen voneinander trennen kannst. Stelle zuerst die Auffangschale, dann das feine Sieb (0,063mm) und zuletzt das gröbere Sieb (2mm) auf die Siebmaschine.",
  "Füll nun deine gemörserte Bodenprobe in die Siebmaschine ein.",
  "Verschließe die Maschine mit dem Deckel und den Schrauben, sodass nichts von deiner Bodenprobe im Raum landet. Nun kannst du die Siebmaschine starten. Das Sieben wird 5 Minuten dauern.",
  "Deine Bodenprobe ist fertig. Nachdem die Bestandteile auseinander gesiebt wurden, können wir sie jetzt wiegen. Öffne den Verschluss und lege das grobe Sieb zur Seite. Der Boden, der sich darin befindet, wird als Bodenskelett bezeichnet und ist für die Bestimmung der Bodenart nicht relevant.",
  "Platziere das erste Sieb auf der Waage und notiere das Gewicht. In diesem Sieb befinden sich die Bodenpartikel die eine Größe zwischen 2mm- 0,063mm haben, also die Sandfraktion. Denk aber daran, dass du das Eigengewicht des Siebs (245g) abziehen musst. ",
  "Nimm die Auffangschale, stelle sie auf die Waage und notiere das Gewicht. In der Auffangschale sind alle Bodenpartikel, die kleiner sind als 0,063mm, also die Ton-/Schlufffraktion. Wenn man diese Partikel voneinander trennen will, müsste man eine sogenannte Schlämmanalyse machen. Denk auch hier daran, dass du das Eigengewicht des Siebs (285g) abziehen musst. ",
  "Super das Experiment ist geschafft!",
  "",
  "",
  "",
  "",
  "Hi! Schön, dass du den Weg in unser virtuelles Lehr Lern-Labor gefunden hast. Ich werde dir durch meine Anleitung helfen das Experiment zum Pflanzenwachstum durchzuführen. An einigen Stellen wirst du den Button „Tipp“ sehen, der dir weitere Hilfestellungen geben wird. Während des Experiments wirst du einige Fragen gestellt bekommen. Zu diesen werde ich dir Feedback geben und dich unterstützen, falls du noch nicht die richtige Lösung kennst.",
  "Vor dir siehst du einen Wachstumsschrank. In diesem können natürliche, aber auch zukünftige klimatische Bedingungen präzise simuliert werden unter denen Pflanzen und Organismen wachsen können. In Hinblick auf das sich verändernde Klima können wir schauen, wie Pflanzen in Zukunft wachsen und, ob sie das überhaupt noch können.",
  "Beginnen wir mit dem Experiment! Stelle jeweils einen Topf mit einem Samen in ein Abteil des Wachstumsschranks.",
  "Schließe die Wachstumsschränke.",
  "An jedem Wachstumsschrank findest du eine Anzeigetafel. Auf dieser kannst du die fünf Parameter sehen, die Einfluss auf das Wachstum der Pflanze haben und verändert werden können. Wenn wir wissen wollen, welcher Parameter genau das Wachstum beeinflusst hat, dürfen wir immer nur einen Parameter verändern, während die Anderen gleichbleiben. Wir können sonst nicht genau unterscheiden, was der Ursprung für die Veränderung ist.",
  "Du kannst dich nun entscheiden, ob du den Einfluss einer veränderter Kohlenstoffdioxid-Konzentration, eine Veränderung der Temperatur oder unterschiedliche Bodenarten näher untersuchen möchtest",
  //CO₂_Konzentration
  "Auf den Anzeigetafeln der Wachstumsschränke kannst du fünf verschiedene Parameter sehen. Die CO2-Konzentration unterscheidet sich bei den drei Wachstumsschränken, während die anderen Parameter gleich sind und den idealen Wachstumsbedingungen von Weizen entsprechen",
  "Ich habe die Werte für den gewählten Parameter bereits für dich ausgewählt",
  "Im ersten Schrank ist ein Wert von 419ppm eingestellt, was dem Jahresmittelwert auf der Zugspitze im Jahr 2022 entspricht. Im 2. Wachstumsschrank beträgt die CO2- Konzentration 550ppm. Im Jahr 2050 würden wir diesen Wert erreichen, wenn wir unseren derzeitigen Kurs behalten und keine Maßnahmen zum Klimaschutz ergreifen. Im letzten Wachstumsschrank beträgt die CO2- Konzentration 650ppm.",
  "In diesem Versuch untersuchen wir, welchen Einfluss eine Erhöhung der CO₂- Konzentration auf das Wachstum von Weizen hat.",
  //Temperatur
  "Auf den Anzeigetafeln der Wachstumsschränke kannst du fünf verschiedene Parameter sehen. Die Temperatur unterscheidet sich bei den drei Wachstumsschränken, während die anderen Parameter den idealen Wachstumsbedingungen von Weizen entsprechen.",
  "Ich habe die Werte für den gewählten Parameter bereits für dich ausgewählt.",
  "Im ersten Schrank beträgt die Temperatur 25 °C, was den idealen Wachstumsbedingungen von Weizen entspricht. Im 2.Wachstumsschrank beträgt die Temperatur 29 °C. Im 3. Wachstumsschrank sind durchgängig 33 °C, um den Einfluss von Hitzeereignissen darzustellen. ",
  "In diesem Versuch untersuchen wir, welchen Einfluss eine Erhöhung der Temperatur auf das Wachstum von Weizen hat.",
  //Bodenart
  "Auf den Anzeigetafeln der Wachstumsschränke kannst du fünf verschiedene Parameter sehen. Die Bodenart unterscheidet sich bei den drei Wachstumsschränken, während die anderen Parameter den idealen Wachstumsbedingungen von Weizen entsprechen.",
  "Ich habe die Werte für den gewählten Parameter bereits für dich ausgewählt.",
  "Im 1.Wachstumsschrank wirst du den Weizen auf einem schluffigen Lehmboden anbauen, was den idealen Bedingungen für Weizen entspricht. Im 2. Wachstumsschrank wird der Weizen auf einem lehmigen Ton angebaut und im 3. Wachstumsschrank auf einem schwach schluffigen Sand. ",
  "In diesem Versuch untersuchen wir daher, inwiefern die unterschiedliche Korngrößenzusammensetzung, Einfluss auf das Wachstum von Weizen hat.",
  "Für das Experiment nutzen wir einen weiteren Vorteil des virtuellen Labors. Normalerweise müssten wir jetzt mehrere Wochen warten, um Veränderungen zu sehen. Wir werden das ganze einfach ein bisschen schneller machen und vorspulen.",
  "Nach 6 Wochen kannst du bereits die ersten Veränderungen deiner Pflanzen sehen. Notiere dir, wie deine Pflanzen aussehen und welche Unterschiede es gibt.",
  //Feedback erste Runde
  "Sehr gute Beobachtung!",
  "Deine Antwort ist leider nicht korrekt. Ich schlage dir vor, dass du deine Pflanze nochmals genau betrachtest.",
  //Feedback zweite Runde 
  "Sehr gut, deine Antwort ist korrekt.",
  //CO₂-Konzentartion
  "Leider ist deine Antwort nicht korrekt. Die richtige Antwort ist die linke. Für die Zukunft würde ich dir vorschlagen, die Fragen und die Antworten in aller Ruhe und gründlich zu lesen.",
  //Temperatur
  "Leider ist deine Antwort nicht korrekt. Die richtige Antwort ist die mittlere. Für die Zukunft würde ich dir vorschlagen, die Fragen und die Antworten in aller Ruhe und gründlich zu lesen.",
  //Bodenart
  "Leider ist deine Antwort nicht korrekt. Die richtige Antwort ist die linke. Für die Zukunft würde ich dir vorschlagen, die Fragen und die Antworten in aller Ruhe und gründlich zu lesen.",
  "Als nächstes schauen wir uns die Veränderungen nach 12 Wochen an.",
  "Wir sehen zwar einen Unterschied im Wachstum der Pflanzen, allerdings wollen wir das Ganze auch noch wissenschaftlich überprüfen. Öffne die Wachstumsschränke.",
  /*70*/"Nimm die Schere und schneide damit den ganzen oberirdischen Teil deiner Pflanze ab und lege ihn in die Petrischale. Wiederhole den Vorgang mit den anderen beiden Pflanzen.",
  "Platziere die Petrischalen nacheinander auf der Waage und notiere das Gewicht. Beachte, dass das Anfangsgewicht der Waage einen Wert von -0,300g anzeigt. Wir haben das Eigengewicht der Petrischale von 300g bereits berücksichtigt.",
  //Feedback
  //CO₂-Konzentration
  "Super, deine Antwort ist richtig.",
  "Deine Antwort ist leider nicht korrekt. Denk daran, dass du die Pflanzen in absteigender Reihenfolge ordnen sollst. Die Pflanze mit dem höchsten Wert kommt also zuerst.",
  "Top! Du hast die richtige Lösung.",
  "Leider ist deine Antwort nicht korrekt. Die richtige Reihenfolge wäre 3-2-1.",
  //Temperatur
  "Leider ist deine Antwort nicht korrekt. Die richtige Reihenfolge wäre 1-2-3.",
  //Bodenart
  "Leider ist deine Antwort nicht korrekt. Die richtige Reihenfolge wäre 1-3-2.",
  //CO₂
  //Feedback erste Runde
  /*78*/"Gut gemacht! Deine Antwort ist korrekt. Mach weiter so!",
  "Deine Antwort ist leider nicht korrekt. Bitte denk nochmal darüber nach, was du im Workshop über den Einfluss von CO₂ auf das Pflanzenwachstum gehört hast, und versuche es noch einmal.",
  //Feedback zweite Runde
  "Sehr gut! Du hast die korrekte Antwort herausgefunden. Mach weiter so und bleib aufmerksam beim Beantworten der Fragen.",
  "Leider ist deine Antwort nicht korrekt. Die richtige Antwort ist die linke. Eine erhöhte CO₂-Konzentration kann das Wachstum von Pflanzen steigern, allerdings leidet die Qualität der Erträge darunter.",
  //Temperatur - richtige Antworten gleich wie bei CO₂
  //Feedback erste Runde
  "Deine Antwort ist leider nicht korrekt. Bitte denk nochmal darüber nach, was du im Workshop über den Einfluss der Temperatur auf das Pflanzenwachstum gehört hast, und versuche es noch einmal.",
  //Feedback zweite Runde
  "Leider ist deine Antwort nicht korrekt. Die richtige Antwort ist die mittlere. Eine moderate Erhöhung der Temperatur kann dazu führen, dass die Fotosyntheseaktivität ansteigt. Allerdings musst du beachten, dass ein Anstieg der Temperatur nur innerhalb des sogenannten Toleranzbereichs möglich ist. Wenn die Temperatur zu hoch, oder zu niedrig ist verlangsam sich die Prozesse innerhalb der Pflanze.",
  //Bodenart - richtige Antworten gleich wie bei CO₂
  //Feedback erste Runde
  "Deine Antwort ist leider nicht korrekt. Bitte denk nochmal darüber nach, was du im Workshop über den Einfluss der Bodenart auf das Pflanzenwachstum gehört hast, und versuche es noch einmal.",
  //Feedback zweite Runde
  "Leider ist deine Antwort nicht korrekt. Die richtige Antwort ist die rechte. Jede Bodenart hat unterschiedliche Eigenschaften, sodass diese das Wachstum von Pflanzen beeinflussen. Einige Böden können aufgrund einer begrenzten Wasserverfügbarkeit das Wachstum einschränken, während andere Bodenarten speziell angepasste Pflanzen unterstützen können.",
  "Super, das Experiment ist geschafft!",
]


export var MANNEQUIN_TEXTS_EXTRA = [
  "",
  "Stell den Mörser mit dem Stößel auf das Hologramm. Du kannst erst mit der Probe weitermachen, wenn die Probe ganz fein gemörsert ist und sich keine zusammenhängenden Klümpchen mehr darin befinden! Diese würden das Ergebnis verfälschen.",
  "Notier das Leergewicht vom Tiegel in deinem Notizbuch! Das ist wichtig, um am Ende den Humusgehalt berechnen zu können. ",
  "Dafür musst du die Taste „TARA“ drücken.",
  "Notier das Gewicht deiner Bodenprobe in deinem Notizbuch.",
  "",
  "",
  "Wenn du den Button „Rühren“ mehrfach  anklickst, läuft die Stoppuhr schneller.",
  "Stell das Thermometer in den Tiegel und achte auf die Temperatur. Leg das Thermometer anschließend wieder auf die Arbeitsfläche.",
  "Wenn du den Button „Rühren“ mehrfach  anklickst, läuft die Stoppuhr schneller.",
  "",
  "",
  "Nimm den Tiegel mit der Tiegelzange und stell sie auf die Waage. Lies das Gewicht ab und notier es in deinem Notizbuch.",
  "",
  "",
  "",
  "Mithilfe eines Bunsenbrenners wird die Bodenprobe für 25 Minuten erhitzt. Humus besteht aus abgestorbenen pflanzlichen und tierischen Stoffen und ist brennbar. Durch das Ausglühen kann über den Gewichtsverlust der prozentuale Humusgehalt der Probe berechnet werden. Und genau das werden wir jetzt im Labor machen!\n      ",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "Das Gewicht der Sandfraktion benötigst du, um die Gesamtmasse des Bodens aber auch um den prozentualen Anteil der Sandfraktion am Gesamtboden zu berechnen.",
  "Das Gewicht der Ton-/Schlufffraktion benötigst du, um die Gesamtmasse des Bodens, aber auch um den prozentualen Anteil der Ton-/Schlufffraktion am Gesamtboden zu berechnen.",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
]

export var MANNEQUIN_TEXTS_BUBBLES = [
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_LOW,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_LOW,
  MANNEQUIN_BUBBLE_LOW,
  MANNEQUIN_BUBBLE_LOW,
  MANNEQUIN_BUBBLE_LOW,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
  MANNEQUIN_BUBBLE_HIGH,
]

